---
- hosts: digitalocean
  connection: local
  gather_facts: false
  
  vars:
    do_token: "{{ lookup('file', '~/DO_Token.txt') }}"
    ssh_key_name: Jacob-Brown-2106
    my_ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    droplet_name:
      - "BrownJ-2106-WordPress1"
      - "BrownJ-2106-WordPress2"

  tasks:
    - name: Create ssh key
      digital_ocean_sshkey:
        oauth_token: "{{ do_token }}"
        name: "{{ ssh_key_name }}"
        ssh_pub_key: "{{ my_ssh_key }}"
        state: present
      register: ssh_key
    - debug:
        msg: The SSH ID is {{ mysshkey.data.ssh_key.id }}

    - name: Create two droplets
      digital_ocean_droplet:
        state: present
        name: "{{ item }}"
        oauth_token: "{{ do_token }}"
        size: s-1vcpu-1gb
        region: nyc1
        unique_name: yes
        image: centos-8-x64
        wait: yes
        ssh_keys: ["{{ mysshkey.data.ssh_key.id }}"]
      with_items: "{{ droplet_name }}"
      register: dropletinfo
    # - debug:
    #     msg: Pubilic IP address is {{ dropletinfo.data.ip_address }}

    # - pause:
    #     minutes: 1

    - name: Add the droplets' IP address to the hosts file.
      add_host:
        name: "{{ item }}"
        groups: droplets
      with_items: [{{ dropletinfo.data.ip_address }}]

- hosts: droplets
  remote_user: root
  gather_facts: false

  vars:
    yansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: wait for port 22 to become available
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
      delegate_to: localhost
    
    - name: Gather Facts
      setup:

    - name:
      selinux:
        state: disabled

    - name: Update CentOS and install dependencies.
      dnf:
        name:
        - '*'
        - epel-release
        - php-mysqlnd
        - php-fpm
        - mariadb-server
        - httpd
        - tar
        - curl
        - php-json
        - git
        update_cache: yes
        state: latest

    - name: Changing the Document Root in Apache
      lineinfile:
        path: /etc/httpd/conf.d
        regexp: '^DocumentRoot "/var/www/html"'
        line: DocumentRoot "/var/www/html/wordpress"

    - name: Start Apache and Mariadb and enable it on boot.
      service:
        name: 
        - httpd
        - mariadb
        state: started
        enabled: yes

    - name: Firewalld enable it on boot
      service:
        name: firewalld
        enabled: yes

    - name: Open port 80
      firewalld:
        zone: public
        service: http
        permanent: yes
        state: enabled

    - name: Restart servace firewalld
      service:
        name: firewalld
        state: restarted

    - name: Reboot
      reboot:
        reboot_timeout: 600

    - name: Check if Apache is running after reboot
      service:
        name: httpd
        state: started

    - name: MariaDB Create Database
      mysql_db:
        name: wordpressdb
        state: present

    - name: WordPress User Database
      mysql_user:
        login_user: root
        name: wordpressuser
        password: Fullsail1!
        priv: '*.*:ALL'
        state: present

    - name: WordPress from GitHub
      ansible.builtin.git:
        repo: https://github.com/WordPress/WordPress.git
        dest: /var/www/html/
        clone: yes
      
    - name: Change Owner and Group of WordPress Files
      file:
        path: /var/www/html/
        state: directory
        mode: 0775
        recurse: yes
        owner: apache
        group: apache

...
